apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - name: grpc-port
    port: 9090
    targetPort: 9090
  - name: http-port
    port: 8081
    targetPort: 8081
  type: ClusterIP  # Internal service, accessible only within the cluster